name: firedart_2
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 1.0.0
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.0.0
  grpc: ^3.1.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  firebase_auth_rest_2: ^2.1.0
  universal_io: ^2.0.4

dev_dependencies:
  test: ^1.17.7
  pedantic: ^1.11.0

dependency_overrides:
  http: ^1.0.0